sudo: false
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode10.2
      cache:
        bundler: true
        cocoapods: true
    - os: linux
      jdk: oraclejdk8
      language: android
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-28.0.3
          - android-22
          - android-28
          - sys-img-armeabi-v7a-android-22
        licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
      cache:
        bundler: true
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
          - demo/node_modules
          - $HOME/.nvm
script:
  - nvm install 10.9.0
  - nvm use 10.9.0
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      rvm use 2.5.1 --install; 
    fi
  - /bin/bash tests/travis.sh || travis_terminate 1;
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
      nvm install 12.14.0;
      nvm use 12.14.0;
      rvm use 2.7.0 --install;
      /bin/bash demo/travis.sh;
    fi

